import React, { useState, useEffect } from 'react';
import { useApp } from '../../hooks/useAppContext';
import { Clock, CheckCircle2, RotateCcw, Award, Zap, BookOpen } from 'lucide-react';
import confetti from 'canvas-confetti';

export const RcLabView: React.FC = () => {
  const { lang } = useApp();
  const [readingPhase, setReadingPhase] = useState<'reading' | 'answering' | 'results'>('reading');
  const [seconds, setSeconds] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});

  const samplePassage = {
    title: 'The Philosophy of Legal Realism and Judicial Behavior',
    wordCount: 385,
    text: `For centuries, classical legal formalism conceptualized adjudication as a mechanical, deductive science. According to the formalist paradigm, judges were merely neutral transmission belts who identified pre-existing, static statutory rules and deduced uncontroversial outcomes through strict formal logic, untainted by subjective human predilections. Law was viewed as a complete, autonomous, and self-contained normative universe.

In the early twentieth century, this mechanistic illusion was forcefully dismantled by the American Legal Realist movement, spearheaded by jurists like Oliver Wendell Holmes Jr., Karl Llewellyn, and Jerome Frank. In his famous dictum in 'The Common Law', Holmes observed that "the life of the law has not been logic: it has been experience." Realists argued that legal rules are inherently open-textured, ambiguous, and indeterminative in hard cases. Words in statutes contain a "penumbra of uncertainty" that forces the judge to make creative policy choices.

Consequently, judicial decisions are not generated by pure syllogisms; they are shaped by the social prejudices, moral philosophies, psychological temperament, and economic worldviews of the judges themselves. Formal legal rules and doctrine often function as post hoc rationalizations crafted to justify conclusions already reached intuitively through subjective gut reactions. 

However, legal realism does not claim that law is complete anarchy or that judges act with unrestrained caprice. Rather, it insists that legal education and scholarship must look beyond the black-letter rules of law books to the actual behavior of actors in the courtroom. Understanding jurisprudence requires empirical sociopolitical analysis of how institutional constraints, collegial dynamics on appellate benches, and evolving societal values channel judicial discretion toward coherent public policies.`,
    questions: [
      {
        type: 'Main Idea',
        question: 'Which of the following statements best synthesizes the primary objective of the passage?',
        options: [
          'To prove that classical legal formalism is the only reliable method for guaranteeing constitutional certainty.',
          'To contrast classical legal formalism with legal realism, showing how realism reveals the subjective and experiential factors influencing judicial decision-making.',
          'To argue that appellate judges should be replaced with automated computational logic models.',
          'To criticize Oliver Wendell Holmes Jr. for undermining judicial ethics in American courts.'
        ],
        answer: 1,
        explanation: 'The passage sets up the formalist view in paragraph 1, contrasts it with realism in paragraphs 2-3, and concludes with a balanced summary of what realism contributes.'
      },
      {
        type: 'Inference',
        question: 'Based on the passage, legal realists would most likely AGREE with which of the following contentions?',
        options: [
          'Judicial decisions in complex cases are entirely decided by clear dictionary definitions of statutory words.',
          'Judges frequently use legal rules and doctrines to provide formal justification for conclusions they have already formed intuitively.',
          'The social and economic backgrounds of judges have zero impact on how constitutional rights are interpreted.',
          'Legal realism advocates for total judicial lawlessness and chaotic anarchy in trials.'
        ],
        answer: 1,
        explanation: 'Paragraph 3 explicitly states: "Formal legal rules and doctrine often function as post hoc rationalizations crafted to justify conclusions already reached intuitively through subjective gut reactions."'
      },
      {
        type: 'Vocabulary',
        question: 'As used in the second paragraph, the phrase "PENUMBRA OF UNCERTAINTY" refers to:',
        options: [
          'A solar eclipse obstructing courtroom proceedings.',
          'The area of ambiguity and borderline cases where the application of a legal rule is not definitively clear.',
          'The unquestionable accuracy of a Supreme Court verdict.',
          'A confidential in-camera criminal witness hearing.'
        ],
        answer: 1,
        explanation: 'In jurisprudence (famously H.L.A. Hart\'s term), the "penumbra of uncertainty" signifies the grey, ambiguous zone where words in a rule do not have an obvious, settled meaning.'
      }
    ]
  };

  // Live timer for reading phase
  useEffect(() => {
    let timer: any = null;
    if (readingPhase === 'reading') {
      timer = setInterval(() => setSeconds((s) => s + 1), 1000);
    }
    return () => clearInterval(timer);
  }, [readingPhase]);

  const handleFinishReading = () => {
    setReadingPhase('answering');
  };

  const handleSelectAnswer = (qIdx: number, optIdx: number) => {
    setSelectedAnswers((prev) => ({ ...prev, [qIdx]: optIdx }));
  };

  const handleFinishQuiz = () => {
    setReadingPhase('results');
    confetti({ particleCount: 40, spread: 50 });
  };

  const handleRestart = () => {
    setReadingPhase('reading');
    setSeconds(0);
    setSelectedAnswers({});
  };

  const wpm = seconds > 0 ? Math.round((samplePassage.wordCount / seconds) * 60) : 0;
  const correctCount = samplePassage.questions.filter((q, idx) => selectedAnswers[idx] === q.answer).length;
  const accuracyPercent = Math.round((correctCount / samplePassage.questions.length) * 100);

  const getPaceFeedback = (rate: number) => {
    if (rate >= 280) return { label: 'Elite CLAT Speed', color: 'text-emerald-500' };
    if (rate >= 220) return { label: 'Good Competitive Pace', color: 'text-indigo-500' };
    if (rate >= 160) return { label: 'Average (Needs Improvement)', color: 'text-amber-500' };
    return { label: 'Slow (Practice Scanning)', color: 'text-rose-500' };
  };

  const feedback = getPaceFeedback(wpm);

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* Banner */}
      <div className="bg-gradient-to-r from-blue-950 via-indigo-950 to-slate-900 text-white rounded-2xl p-6 md:p-8 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-xs font-semibold uppercase text-blue-300 mb-2 border border-white/10">
            <Clock className="w-3.5 h-3.5" />
            <span>Reading Comprehension Laboratory</span>
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight">
            Reading Speed (WPM) & Comprehension Audit
          </h1>
          <p className="text-slate-300 text-xs md:text-sm mt-1 max-w-xl">
            {lang === 'hi' 
              ? 'अपनी वास्तविक पढ़ने की गति (शब्द प्रति मिनट) और समझ प्रतिधारण दर का परीक्षण करें।'
              : 'Measure your reading speed in Words Per Minute (WPM), eliminate subvocalization, and verify comprehension retention.'}
          </p>
        </div>

        {/* Live Metrics */}
        <div className="flex items-center gap-4 bg-white/10 backdrop-blur-md p-3.5 rounded-2xl border border-white/10 shrink-0">
          <div className="text-center px-2">
            <span className="text-[10px] text-blue-200 uppercase font-bold block">{lang === 'hi' ? 'समय' : 'Reading Time'}</span>
            <span className="text-xl font-mono font-bold">{seconds}s</span>
          </div>
          <div className="w-px h-8 bg-white/20" />
          <div className="text-center px-2">
            <span className="text-[10px] text-blue-200 uppercase font-bold block">{lang === 'hi' ? 'पठन गति' : 'Reading Rate'}</span>
            <span className="text-xl font-bold text-blue-300">{wpm} WPM</span>
          </div>
        </div>
      </div>

      {/* Main Flow */}
      {readingPhase === 'reading' && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-xs space-y-4 max-w-4xl mx-auto">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase">
                Phase 1: Speed Reading Sprint
              </span>
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mt-0.5">
                {samplePassage.title}
              </h2>
            </div>
            <span className="text-xs font-semibold px-2.5 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
              {samplePassage.wordCount} words
            </span>
          </div>

          <div className="prose dark:prose-invert max-w-none text-sm md:text-base text-slate-800 dark:text-slate-200 leading-relaxed space-y-4 py-2 font-serif">
            {samplePassage.text.split('\n\n').map((para, idx) => (
              <p key={idx}>{para}</p>
            ))}
          </div>

          <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
            <span className="text-xs text-slate-500">
              {lang === 'hi' ? 'पूरा पढ़ने के बाद नीचे दिए गए बटन पर क्लिक करें' : 'Click the button immediately when you finish reading to record exact WPM'}
            </span>
            <button
              onClick={handleFinishReading}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl font-bold text-xs md:text-sm bg-indigo-600 hover:bg-indigo-700 text-white shadow-md shadow-indigo-500/20 transition-all"
            >
              <span>{lang === 'hi' ? 'पढ़ना पूरा हुआ! प्रश्न हल करें' : 'I Finished Reading! Start Questions'}</span>
              <Zap className="w-4 h-4 text-amber-300" />
            </button>
          </div>
        </div>
      )}

      {readingPhase === 'answering' && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-xs space-y-6 max-w-4xl mx-auto">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 uppercase">
                Phase 2: Retention & Comprehension Check
              </span>
              <h2 className="text-lg font-bold text-slate-900 dark:text-white">
                Answer without re-reading the passage text
              </h2>
            </div>
            <span className="text-xs font-mono font-bold text-indigo-600 dark:text-indigo-400">
              Recorded Pace: {wpm} WPM ({seconds}s)
            </span>
          </div>

          <div className="space-y-6">
            {samplePassage.questions.map((q, qIdx) => (
              <div key={qIdx} className="space-y-3 p-4 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-800">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold px-2 py-0.5 rounded bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300">
                    {q.type}
                  </span>
                  <span className="text-xs text-slate-400">Question {qIdx + 1} of {samplePassage.questions.length}</span>
                </div>

                <p className="text-sm font-semibold text-slate-900 dark:text-white">
                  {q.question}
                </p>

                <div className="space-y-2">
                  {q.options.map((opt, optIdx) => {
                    const isSelected = selectedAnswers[qIdx] === optIdx;
                    return (
                      <button
                        key={optIdx}
                        onClick={() => handleSelectAnswer(qIdx, optIdx)}
                        className={`w-full p-3 rounded-lg text-xs md:text-sm text-left border transition-all flex items-start gap-2.5 ${
                          isSelected
                            ? 'bg-indigo-50 dark:bg-indigo-950 border-indigo-600 text-indigo-800 dark:text-indigo-200 font-semibold'
                            : 'border-slate-200 dark:border-slate-700 hover:bg-white dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300'
                        }`}
                      >
                        <span className="w-5 h-5 rounded-full border border-current flex items-center justify-center text-xs shrink-0 font-bold">
                          {String.fromCharCode(65 + optIdx)}
                        </span>
                        <span>{opt}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>

          <div className="pt-2 flex justify-end">
            <button
              onClick={handleFinishQuiz}
              disabled={Object.keys(selectedAnswers).length < samplePassage.questions.length}
              className="px-6 py-2.5 rounded-xl font-bold text-xs md:text-sm bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-50 transition-colors shadow-md"
            >
              {lang === 'hi' ? 'परिणाम और ऑडिट देखें' : 'View Performance Audit'}
            </button>
          </div>
        </div>
      )}

      {readingPhase === 'results' && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 md:p-8 border border-slate-200 dark:border-slate-800 shadow-xs space-y-6 max-w-4xl mx-auto">
          <div className="text-center space-y-2">
            <div className="w-16 h-16 rounded-2xl bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 mx-auto flex items-center justify-center">
              <Award className="w-8 h-8" />
            </div>
            <h2 className="text-2xl font-black text-slate-900 dark:text-white">
              {lang === 'hi' ? 'आरसी लैब प्रदर्शन ऑडिट' : 'RC Lab Performance Audit'}
            </h2>
            <p className="text-xs md:text-sm text-slate-500 max-w-md mx-auto">
              Diagnostic metrics comparing reading pace against comprehension accuracy
            </p>
          </div>

          {/* Metrics Scorecard */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-slate-50 dark:bg-slate-800/60 p-4 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-xs text-slate-400 font-bold uppercase block">Pace Category</span>
              <span className={`text-xl font-bold ${feedback.color} mt-1 block`}>{feedback.label}</span>
              <span className="text-xs text-slate-500 mt-1 block">{wpm} WPM ({seconds} seconds)</span>
            </div>

            <div className="bg-slate-50 dark:bg-slate-800/60 p-4 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-xs text-slate-400 font-bold uppercase block">Comprehension Accuracy</span>
              <span className="text-xl font-bold text-indigo-600 dark:text-indigo-400 mt-1 block">
                {accuracyPercent}%
              </span>
              <span className="text-xs text-slate-500 mt-1 block">
                {correctCount} / {samplePassage.questions.length} Correct
              </span>
            </div>

            <div className="bg-slate-50 dark:bg-slate-800/60 p-4 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-xs text-slate-400 font-bold uppercase block">Target CLAT Benchmark</span>
              <span className="text-xl font-bold text-emerald-600 dark:text-emerald-400 mt-1 block">
                250–300 WPM
              </span>
              <span className="text-xs text-slate-500 mt-1 block">&gt;80% Accuracy Retention</span>
            </div>
          </div>

          {/* Solution Explanations */}
          <div className="space-y-4 pt-4 border-t border-slate-200 dark:border-slate-800">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">
              {lang === 'hi' ? 'प्रश्नों का विस्तृत हल' : 'Question-by-Question Solution Analysis'}
            </h3>
            {samplePassage.questions.map((q, idx) => {
              const uAns = selectedAnswers[idx];
              const isCorrect = uAns === q.answer;
              return (
                <div key={idx} className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 space-y-2 text-xs md:text-sm">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-900 dark:text-white">Q{idx + 1}: {q.question}</span>
                    <span className={`text-xs font-bold px-2 py-0.5 rounded ${
                      isCorrect ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'
                    }`}>
                      {isCorrect ? 'Correct' : 'Missed'}
                    </span>
                  </div>
                  <p className="text-slate-600 dark:text-slate-400 text-xs">
                    <strong>Your Choice:</strong> {String.fromCharCode(65 + uAns)}: {q.options[uAns]}
                  </p>
                  {!isCorrect && (
                    <p className="text-emerald-600 dark:text-emerald-400 text-xs font-semibold">
                      <strong>Correct Answer:</strong> {String.fromCharCode(65 + q.answer)}: {q.options[q.answer]}
                    </p>
                  )}
                  <p className="text-xs text-slate-500 dark:text-slate-400 border-t border-slate-100 dark:border-slate-800 pt-1.5">
                    <strong>Rationale:</strong> {q.explanation}
                  </p>
                </div>
              );
            })}
          </div>

          <div className="pt-2 flex justify-center">
            <button
              onClick={handleRestart}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs md:text-sm font-bold bg-slate-900 dark:bg-white text-white dark:text-slate-900 hover:opacity-90 transition-opacity"
            >
              <RotateCcw className="w-4 h-4" />
              <span>{lang === 'hi' ? 'पुनः प्रयास करें' : 'Run New Speed Sprint'}</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
